config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :user_units
  resources :user_courses
  
  resources :courses do
    resources :units do
      member do
        post :compare
      end
    end
  end

 root 'home#index'

 get '/students', to: 'students#index'
 
 get '/energies', to: 'energies#index'

 get '/users/:nickname', to: 'users#show', as: :profile

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable


  
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :user_course
	has_many :users, through: :user_course
	

	has_many :units

	def number_of_units
		self.units.count
	end

end

app/models/energy.rb
class Energy < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :user_unit
	has_many :users, through: :user_unit
	belongs_to :course

	def unitprog(user)
      user.units.last
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_course
  has_many :courses, through: :user_course

  has_many :user_unit
  has_many :units, through: :user_unit
  mount_uploader :avatar, AvatarUploader

  devise :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
       user.nickname = auth.info.name
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
 


  def units_per_course(id_course)
  	units = Course.find(id_course).units.pluck(:id) # [5,6,7,8]
  	self.user_units.where(unit_id: units).count
  end


end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	belongs_to :user
	belongs_to  :course
end

app/models/user_unit.rb
class UserUnit < ActiveRecord::Base

	belongs_to :user
	belongs_to  :unit


	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@courses = Course.all

    end 

    


end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  before_action :set_course
  before_filter :authenticate_user!, only: [:show]

   def set_course
    @course= Course.find(params[:course_id])
    end 

  

  # GET /units
  # GET /units.json
  def index
    @course= Course.find(params[:course_id])
    @units = @course.units.all
     
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @course= Course.find(params[:course_id])
   @unit= @course.units.find(params[:id]) 
   current_user.courses << @course unless current_user.courses.include?(@course)
  end

  # GET /units/new
  def new
    @course= Course.find(params[:course_id])
    @unit = @course.units.new
    
  end

  # GET /units/1/edit
  def edit
    @course= Course.find(params[:course_id])
    @unit= @course.units.find(params[:id]) 
  end

  # POST /units
  # POST /units.json
  def create
    @course= Course.find(params[:course_id])
   
    @unit=@course.units.new(unit_params)
       
    @course.save
    redirect_to course_units_path
  end

  def compare
    @course = Course.find(params[:course_id])
    @unit = @course.units.find(params[:id])
    simulador = params[:simulador]

    respuesta = @unit.answer.downcase.gsub(/\s+/, "") == simulador.downcase.gsub(/\s+/, "") 
    if respuesta
      current_user.units << @unit unless current_user.units.include?(@unit)
    end
    respuesta = render(partial: "respuesta", locals: { respuesta: respuesta })
    #render json: { respuesta: respuesta }, status: :ok
  end

 


  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    @unit= @course.units.find(params[:id])
    @unit.update(unit_params) 
    redirect_to course_units_path


    
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
     @unit= @course.units.find(params[:id])
    @unit.destroy
    redirect_to course_units_path
  end
   

  private
    # Use callbacks to share common setup or constraints between actions.
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:description, :name, :course_id, :content, :simulator, :answer, :content2, :content3)

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 

  def show
    @user = User.find_by_nickname(params[:nickname])
    redirect_to user_not_found_path if @user.nil?
  end

  def user_not_found
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/energies_helper.rb
module EnergiesHelper
end

app/helpers/energy_helper.rb
module EnergyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/units_helper.rb
module UnitsHelper

	

end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/helpers/user_units_helper.rb
module UserUnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!--Contenedor Global -->
<div class="contenedorGlobal">

<!-- Encabezado -->

  <div class="contenedor">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <nav class="navegador">
  <!-- contenedor del menu -->
  <div>
   <!-- Lista de menu -->
  <div class="menu">
  <ul>
  <li><a href="#" class="scroll hvr-underline-from-center">Equipo</a></li>
  <li><a href="#" class="scroll hvr-underline-from-center">Cursos</a></li>
  <li><a href="#vision" class="scroll hvr-underline-from-center">Visión</a></li>        
  <li><a href="#palabras" class="scroll hvr-underline-from-center">Nuestra filosofía</a></li>       
  </ul>
  </div>
  </div>
</nav>
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div id="fondo"class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "fondo2.jpg", alt: "fondo" %>
      <div class="carousel-caption">
        <h1 class="textos2"> Paso a paso se aprende mejor! </h1>
      </div>
    </div>

    <div class="item">
      <%= image_tag "fondo1.jpg", alt: "fondo" %>
      <div class="carousel-caption">
        <h1 class="textos"> Aprende arduino y Energias renovables </h1>
        </div>
    </div>
    <div class="item">
      <%= image_tag "fondo.jpg", alt: "textos" %>
      <div class="carousel-caption">
        <h1 class="textos3">Ciencia y tecnológica a tu alcance</h1>
      </div>
    </div>
  </div>
</div>  
</div>
    
<!-- Final navegador-->
<!-- Seccion 1-->  

<!-- seccion 2-->
    <div id="palabras">
    
    <!-- iconos y cuadros-->
        <section class="cuadro">
        
        <a href="#0" >
          <span ><%= image_tag "educacion.png", class: "icon", alt: "IconoEducacion" %></span>
          <h3>Educación</h3>
          <p>Experiencias significativas que evocan y motivan un aprendizaje constructivo</p>
        </a>

        <a href="#0">
          <span><%= image_tag "exclusivo.png", class: "icon", alt: "IconoExclusividad" %></span>
          <h3>Exclusividad</h3>
          <p>Asesorías personalizadas de acuerdo a las necesidades de cada usuario</p>
        </a>

        <a href="#0">
          <span><%= image_tag "tiempo.png", class: "icon", alt: "IconoTiempo" %></span>
          <h3>Flexibilidad</h3>
          <p>Aprende en cualquier horario desde la comodidad de tu hogar y a tu propia ritmo</p>
        </a>

        </section>
        <!--final iconos-->
    <!-- información-->

        <section class="filosofia" >

        <h2>Actividades Claves</h2>
        
        </section>

    </div>
<!-- seccion 3-->

    <div id="vision" class="seccion3">
    <section class="somos">
    <h2>Filosofía</h2>
        <p>Creemos en un conocimiento universal y accesible para fomentar la creatividad y el mejoramiento continuo de los procesos formativos.
        </p>
        </section>
        
        <%= image_tag "filosofia.png", class: "imagenes", alt: "filosofiaEmpresarial" %>
    </div>

    <div class="seccion3">
      <%= image_tag "vision.png", class: "imagenes imgVision", alt: "Vision" %>
       <section class="vision">
    <h2>Visión</h2>
        <p>Nos proyectamos hacia una sociedad de conocimiento donde los jovenes generen nuevas tecnologias y construyan propuestas que pretendan solucionar las problematicas del entorno actual.
        </p>
        </section>


    </div>
<!-- final seccion3-->
<!--Contactanos-->
<div class="cursos">
<h1>Cursos </h1>

<div id="ex4" >
<%= image_tag "cursos-01.png", alt: "Energías" %>
<h2>Robotica al calcance de tu mano</h2>
<p>Aprende a programar codigo
</p>
</div>

<div id="ex5" >
<%= image_tag "cursos-02.png", alt: "Energías" %>
<h2>La mejor forma de pensar en el futuro</h2>
<p>Aprende Sobre las energias renovables 
</p>

<div>
<tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.name, course %></td>
      </tr>
    <% end %>
  </tbody>

  <%=link_to  "energias",energies_path%>
  

</div>
</div>


</div>
</div>
</div>



