config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :user_units
  resources :user_courses
  
  resources :courses do
    resources :units do
      member do
        post :compare
      end
    end
  end

 root 'home#index'

 get '/students', to: 'students#index'
 
 get '/energies', to: 'energies#index'

 get '/users/:nickname', to: 'users#show', as: :profile

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable


  
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :user_course
	has_many :users, through: :user_course
	

	has_many :units

	def number_of_units
		self.units.count
	end

end

app/models/energy.rb
class Energy < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :user_unit
	has_many :users, through: :user_unit
	belongs_to :course

	def unitprog(user)
      user.units.last
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_course
  has_many :courses, through: :user_course

  has_many :user_unit
  has_many :units, through: :user_unit
  mount_uploader :avatar, AvatarUploader

  devise :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
       user.nickname = auth.info.name
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
 


  def units_per_course(id_course)
  	units = Course.find(id_course).units.pluck(:id) # [5,6,7,8]
  	self.user_units.where(unit_id: units).count
  end


end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	belongs_to :user
	belongs_to  :course
end

app/models/user_unit.rb
class UserUnit < ActiveRecord::Base

	belongs_to :user
	belongs_to  :unit


	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@courses = Course.all

    end 

    


end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  before_action :set_course
  before_filter :authenticate_user!, only: [:show]

   def set_course
    @course= Course.find(params[:course_id])
    end 

  

  # GET /units
  # GET /units.json
  def index
    @course= Course.find(params[:course_id])
    @units = @course.units.all
     
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @course= Course.find(params[:course_id])
   @unit= @course.units.find(params[:id]) 
   current_user.courses << @course unless current_user.courses.include?(@course)
  end

  # GET /units/new
  def new
    @course= Course.find(params[:course_id])
    @unit = @course.units.new
    
  end

  # GET /units/1/edit
  def edit
    @course= Course.find(params[:course_id])
    @unit= @course.units.find(params[:id]) 
  end

  # POST /units
  # POST /units.json
  def create
    @course= Course.find(params[:course_id])
   
    @unit=@course.units.new(unit_params)
       
    @course.save
    redirect_to course_units_path
  end

  def compare
    @course = Course.find(params[:course_id])
    @unit = @course.units.find(params[:id])
    simulador = params[:simulador]

    respuesta = @unit.answer.downcase.gsub(/\s+/, "") == simulador.downcase.gsub(/\s+/, "") 
    if respuesta
      current_user.units << @unit unless current_user.units.include?(@unit)
    end
    respuesta = render(partial: "respuesta", locals: { respuesta: respuesta })
    #render json: { respuesta: respuesta }, status: :ok
  end

 


  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    @unit= @course.units.find(params[:id])
    @unit.update(unit_params) 
    redirect_to course_units_path


    
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
     @unit= @course.units.find(params[:id])
    @unit.destroy
    redirect_to course_units_path
  end
   

  private
    # Use callbacks to share common setup or constraints between actions.
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:description, :name, :course_id, :content, :simulator, :answer, :content2, :content3)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/energies_helper.rb
module EnergiesHelper
end

app/helpers/energy_helper.rb
module EnergyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/units_helper.rb
module UnitsHelper

	

end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/helpers/user_units_helper.rb
module UserUnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appwissen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>
<body>

<header >
 <nav>
<div class="logo">
  <%= image_tag "logos2.png", class: "imgLogo", alt: "logo" %>
  </div>
  <div class="well well-lg">
  <div class="derecha">

<% if user_signed_in? %>
  Has ingresado con <strong><%= current_user.name %></strong>.
  <%= link_to 'Editar', edit_user_registration_path, :class => 'navbar-link' %> 

  <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <p>Hola <%= link_to current_user.name, profile_path(nickname: current_user.nickname) %>  <%= image_tag(current_user.avatar_url.nil? ?  "foto.png" : current_user.avatar_url, class: "imgAvatar")%></p>
 

<% else %>

<a href="#" class="btn btn-success navbar-btn btn-juli" data-toggle="modal" data-target="#ModalRegistration"><span class="glyphicon glyphicon-user"></span>Sign up</a>
<a href="#" class="btn btn-success navbar-btn" data-toggle="modal" data-target="#myModal">Login</a>

<a class=" btn btn-success navbar-btn btn-social btn-facebook" href="<%=user_omniauth_authorize_path(:facebook)%>">
  <span class="fa fa-facebook"></span>
  Sign in with Facebook
</a>
<% end %>

</div>
</div>
</nav>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<%= render partial: 'partials/login' %>


<%= render partial: 'partials/modal_registro' %>  


</body>
</html>

app/views/partials/_login.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/login_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_login_form.html.erb
<%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Log in", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/partials/_modal_registro.html.erb
<div class="modal fade" id="ModalRegistration" tabindex="-1" role="dialog" aria-labelledby="ModalRegistration">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="ModalRegistrationLabel">Sign up</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/registration_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_registration_form.html.erb
<%= form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>

   <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>